environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      BOOST_LIB: "1_71_0"
      MSVC_TOOLSET: "14.2"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_LIB: "1_66_0"
      MSVC_TOOLSET: "14.1"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BOOST_LIB: "1_60_0"
      MSVC_TOOLSET: "14.0"

matrix:
  allow_failures:
    - image: Visual Studio 2019

version: 1.0.{build}
install:
- ps: |
    C:\Python37-x64\python.exe -m pip install --no-cache-dir --no-warn-script-location --upgrade pip
    C:\Python37-x64\python.exe -m pip install --upgrade --no-warn-script-location setuptools
    C:\Python37-x64\python.exe -m pip install --upgrade --no-warn-script-location wheel
    C:\Python37-x64\Scripts\pip.exe install 'scons>=3.1,<3.2'
    C:\Python37-x64\Scripts\pip.exe install --no-cache-dir --no-warn-script-location numpy
    C:\Python37-x64\Scripts\pip.exe install --no-warn-script-location cython
    C:\Python37-x64\Scripts\pip.exe install pypiwin32
    C:\Python37-x64\Scripts\pip.exe install ruamel.yaml

build_script:
- cmd: C:\Python37-x64\Scripts\scons build boost_inc_dir=C:\Libraries\boost_%BOOST_LIB% debug=n VERBOSE=y python_package=full msvc_version=%MSVC_TOOLSET% -j2
- cmd: C:\Python37-x64\Scripts\scons samples

test_script:
- ps: |
    C:\Python37-x64\Scripts\scons test;
    $env:sconsstatus = $lastexitcode
